# Generated by Django 4.2.2 on 2023-07-03 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfprocessor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('highlights', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
