# Generated by Django 4.2.2 on 2025-01-06 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdfprocessor', '0004_alter_pdf_user_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
